[package]
name = "morok-codegen"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
morok-dtype = { path = "../dtype" }
morok-ir = { path = "../ir" }
morok-device = { path = "../device" }
morok-schedule = { path = "../schedule" }
inkwell = { version = "0.7.1", features = ["llvm21-1"] }
snafu = "0.8.9"
itertools = "0.14.0"
cranelift-codegen = "0.126"
cranelift-frontend = "0.126"
cranelift-native = "0.126"

[dev-dependencies]
smallvec = "1.15.1"
test-case = "3.3.1"
