[package]
name = "morok-ir"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
morok-dtype = { path = "../dtype" }
morok-device = { path = "../device" }
smallvec = "1.15.1"
snafu = "0.8.9"
itertools = "0.14.0"
